apiVersion: v1
kind: Service
metadata:
  name: home-service
  namespace: apollo
  labels:
    app: home-service
    component: microservice
spec:
  selector:
    app: home-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  type: ClusterIP 