services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=apollo_db
      - POSTGRES_PASSWORD=postgreS
      - POSTGRES_USER=faur
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis:/data

