services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=apollo_db
      - POSTGRES_PASSWORD=postgreS
      - POSTGRES_USER=faur
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis:/data

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - '1883:1883'
  #    - '9001:9001' # webSocket listener
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus