---
# Mosquitto Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: apollo
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    allow_anonymous true
    listener 1883
    protocol mqtt
    listener 9001
    protocol websockets

---
# Mosquitto Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: apollo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Mosquitto Logs PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-logs-pvc
  namespace: apollo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
# Mosquitto MQTT Broker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: apollo
  labels:
    app: mosquitto
    component: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        component: mqtt-broker
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.18
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 9001
          name: websockets
          protocol: TCP
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
          readOnly: true
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-logs
          mountPath: /mosquitto/log
        livenessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data-pvc
      - name: mosquitto-logs
        persistentVolumeClaim:
          claimName: mosquitto-logs-pvc

---
# Mosquitto Service
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: apollo
  labels:
    app: mosquitto
    component: mqtt-broker
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: websockets
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP 