apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: apollo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-gateway
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: apollo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: user-service
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
  namespace: apollo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: device-service
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-analysis-service
  namespace: apollo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: media-analysis-service
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-service
  namespace: apollo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: home-service
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m" 