# --- Postgres ----------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: apollo
spec:
  type: LoadBalancer
  ports:
  - port: 5432        # inside-cluster
    targetPort: 5432  # container
  selector:
    app: postgres

# --- Mosquitto ---------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: apollo
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: websockets-ext
    port: 1884
    targetPort: 9001
  selector:
    app: mosquitto

# --- MinIO S3 API -----------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: apollo
spec:
  type: LoadBalancer
  ports:
  - name: minio
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio
