apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: apollo
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        args:
        - "--web.listen-address=0.0.0.0:9187"
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_URI
          value: "localhost:5432/apollo_db?sslmode=disable"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: db-username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: db-password
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi" 
