package ro.faur.apollo.home.domain;

public enum DeviceAccessRights {
    VIEW_IMAGES,
    VIEW_LIVE_STREAM,
    VIEW_NOTIFICATIONS,
    UNLOCK_DOOR,
    ENROLL_FINGERPRINT,
    DELETE_FINGERPRINT,
    ENROLL_FACE,
    DELETE_FACE,
    ENROLL_RFID,
    DELETE_RFID,
    VIEW_DEVICE_INFO,
    VIEW_DEVICE_SETTINGS,
} 