apiVersion: v1
kind: Service
metadata:
  name: media-analysis-service
  namespace: apollo
  labels:
    app: media-analysis-service
spec:
  selector:
    app: media-analysis-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP 