apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: apollo
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
  type: ClusterIP 