scrape_configs:
  - job_name: 'spring-boot-apollo'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/bucket
    scrape_interval: 3s
    scheme: http
    static_configs:
      - targets: [ 'host.docker.internal:9000' ]
