apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: apollo
  labels:
    app: notification-service
    component: microservice
spec:
  selector:
    app: notification-service
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  type: ClusterIP 