apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
  namespace: apollo
  labels:
    app: file-storage-service
    component: microservice
spec:
  selector:
    app: file-storage-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  type: ClusterIP 