management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    enable:
      all: true
    enabled: true
    tags:
      application: apollo-app
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      access: unrestricted
  health:
    enabled: true
    database:
      enabled: true
    redis:
      enabled: true
    jms:
      enabled: true
    cassandra:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true